<?php

namespace App\Http\Requests\Product;

use Illuminate\Foundation\Http\FormRequest;

class SaveProduct extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
          'barcode'=>['unique:products'],
          'name'=>['required','unique:products'],
          'cat'=>['required'],
          'scat'=>['required'],
          'unit'=>['required'],
          'urate'=>['required'],
          'keepStock'=>['required'],
          'feature'=>['required'],
          'new'=>['required'],
        ];
    }

    public function messages()
    {
        $data=[

            'keepStock.required'=>'The maintain stock field is required.',
            'urate.required'=>'The unit rate field is required.'
        ];

        return array_merge(parent::messages(),$data); // TODO: Change the autogenerated stub
    }
}
